#!/bin/bash

set -x

USERNAME=tableauops
PASSWORD=foobar123
INSTALLER=/opt/tableau/tableau_server_automated_installer/automated-installer*/automated-installer

#XXX Secrets needs to be generated
cat <<EOF > /etc/tableau/secrets
# You can use this as a template for the secrets file used with the
# automated-installer script.
#
# Note: If you do not enter the tsm_admin_pass or the
# tableau_server_admin_pass in this file, you will be prompted to enter this
# information during installation. However, you must enter the account names
# for tsm_admin_user and tableau_server_admin_user.

# Credentials for the account that is running the automated-installer script.
# This account will be added to the 'tsmadmin' group. The 'tsmadmin' group is
# created during the Tableau installation process. Members of the 'tsmadmin'
# group can run TSM commands.
#
tsm_admin_user="$USERNAME"
tsm_admin_pass="$PASSWORD"

# Enter a username and password to create the initial Tableau administrator
# account. This account will be created in Tableau Server by the installation
# process and will have Tableau Server administrator rights. The user account
# will be local to Tableau Server and will not be a Linux OS account. If you
# are using LDAP or AD for authentication, then the account you specify for
# the Tableau administrator must be a valid account from the directory service.
#
tableau_server_admin_user="nubis"
tableau_server_admin_pass="foobar123"
EOF

useradd -m -r $USERNAME
echo "$PASSWORD" | passwd $USERNAME --stdin


NUBIS_PROJECT=$(nubis-metadata NUBIS_PROJECT)
NUBIS_ENVIRONMENT=$(nubis-metadata NUBIS_ENVIRONMENT)
LICENSE=$(consulate kv get "$NUBIS_PROJECT-$NUBIS_ENVIRONMENT/$NUBIS_ENVIRONMENT/config/License")

if [ -n "$LICENSE" ]; then
  LICENSE_ARGS="-k $LICENSE"
fi

cd /opt && LANG=en_US.UTF-8 USER=root SUDO_USER=root $INSTALLER --debug -a $USERNAME $LICENSE_ARGS -s /etc/tableau/secrets -f /etc/tableau/config.json -r /etc/tableau/reg.json --accepteula tableau-server-*.rpm
